# Clinical Trial Prediction System Configuration

database:
  type: json
  path: null
  url: null

api:
  clinicaltrials_base_url: https://clinicaltrials.gov/api/v2/studies
  openai_model: gpt-4o-mini
  request_timeout: 30
  rate_limit_delay: 0.1

processing:
  page_size: 1000
  max_pages: 5
  batch_size: 100
  max_retries: 3
  readability_threshold: 10.0
  min_question_words: 8
  max_question_words: 30
  qc_sample_rate: 0.1

data_dir: data
config_dir: config
logs_dir: logs
log_level: INFO
log_format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}'